
#General settings
[general]
	#The name of the group that will be broadcast
	broadcast_group_name = "broadcast"
	#The permission level required to use the broadcast command
	#Range: 0 ~ 4
	permission_level = 2

